# Generated by Django 3.1.4 on 2021-04-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=0, max_length=130),
            preserve_default=False,
        ),
    ]
